#target illustrator

(function () {
    function fail(message) { throw new Error(message); }
    function cfg(name, fallback) {
        if (typeof SI_CONFIG !== 'undefined' && SI_CONFIG && SI_CONFIG[name] !== undefined && SI_CONFIG[name] !== null && SI_CONFIG[name] !== '') return SI_CONFIG[name];
        return fallback;
    }
    function startsWithSi(name) { return String(name).indexOf('SI_') === 0; }
    function findLayer(doc, name) { try { return doc.layers.getByName(name); } catch (e) { return null; } }
    function hasGeneratedMarker(layer) { try { layer.groupItems.getByName('__SI_GENERATED__'); return true; } catch (e) { return false; } }
    function uniqueLayerName(doc, baseName) {
        var candidate = baseName, index = 1;
        while (findLayer(doc, candidate)) { candidate = baseName + '_' + ('0' + index).slice(-2); index += 1; }
        return candidate;
    }

    if (app.documents.length === 0) fail('No Illustrator document is open.');
    var doc = app.activeDocument;
    var svgPath = cfg('svgPath', '');
    var requestedLayer = String(cfg('layerName', 'SI_redraw'));
    var fitMode = String(cfg('fitMode', 'none')).toLowerCase();
    var margin = Number(cfg('marginPoints', 18));
    var replaceGenerated = Boolean(cfg('replaceGeneratedLayer', false));
    if (!svgPath) fail('svgPath is missing from SI_CONFIG.');
    if (!startsWithSi(requestedLayer)) fail('Generated layer names must begin with SI_.');
    if (fitMode !== 'contain' && fitMode !== 'artboard' && fitMode !== 'none') fail('Unsupported fitMode: ' + fitMode);

    var svgFile = new File(svgPath);
    if (!svgFile.exists) fail('SVG file does not exist: ' + svgPath);
    var existing = findLayer(doc, requestedLayer);
    var layerName = requestedLayer;
    if (existing && replaceGenerated) {
        if (!startsWithSi(existing.name) || !hasGeneratedMarker(existing)) fail('Refusing to replace a layer that is not marked as generated by scientific-illustrator.');
        if (existing.locked) fail('Generated layer is locked; unlock it before replacement: ' + existing.name);
        existing.remove();
    } else if (existing) {
        layerName = uniqueLayerName(doc, requestedLayer);
    }

    var layer = doc.layers.add(); layer.name = layerName; layer.visible = true; layer.locked = false;
    var marker = layer.groupItems.add(); marker.name = '__SI_GENERATED__'; marker.hidden = true;
    var placed = layer.placedItems.add(); placed.file = svgFile; app.redraw();
    var artboardIndex = doc.artboards.getActiveArtboardIndex();
    var rect = doc.artboards[artboardIndex].artboardRect;
    var left = rect[0], top = rect[1], right = rect[2], bottom = rect[3];
    var artWidth = right - left, artHeight = top - bottom;
    if (fitMode === 'contain') {
        var availableWidth = Math.max(1, artWidth - (2 * margin));
        var availableHeight = Math.max(1, artHeight - (2 * margin));
        if (placed.width > 0 && placed.height > 0) {
            var scalePct = Math.min(availableWidth / placed.width, availableHeight / placed.height) * 100;
            placed.resize(scalePct, scalePct, true, true, true, true, scalePct, Transformation.CENTER);
            app.redraw(); placed.left = left + ((artWidth - placed.width) / 2); placed.top = top - ((artHeight - placed.height) / 2);
        }
    } else if (fitMode === 'artboard') {
        if (!(placed.width > 0 && placed.height > 0)) fail('Imported SVG has invalid bounds for artboard mapping.');
        var scaleX = (artWidth / placed.width) * 100, scaleY = (artHeight / placed.height) * 100;
        placed.resize(scaleX, scaleY, true, true, true, true, 100, Transformation.TOPLEFT); app.redraw();
        placed.left = left; placed.top = top;
    }
    placed.embed(); app.redraw();
    return 'PLACE_SVG_OK|svg=' + svgPath + '|layer=' + layerName + '|fit=' + fitMode + '|artboard=' + artboardIndex + '|replaced=' + replaceGenerated;
})();
